CONFIG_CAN=y
CONFIG_GPIO=y
CONFIG_REBOOT=y
CONFIG_LOG=y
CONFIG_MAIN_STACK_SIZE=2048

CONFIG_CANOPENNODE=y
CONFIG_CANOPENNODE_SYNC_THREAD=y
CONFIG_CANOPENNODE_LEDS=n
CONFIG_CANOPENNODE_STORAGE=n

# Program download (MCUboot is enabled in sysbuild.conf)
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_CANOPENNODE_PROGRAM_DOWNLOAD=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y

# Version signed into the MCUboot header, bump it for each new image
CONFIG_MCUBOOT_IMGTOOL_SIGN_VERSION="1.0.0"
